version: '3.5'

services:

  i2b2-web:
    image: i2b2/i2b2-web:${I2B2_WEB_TAG}
    container_name: i2b2-web
    ports:
      - "80:80"
      - "443:443"
    command: /run-httpd.sh localhost
    networks:
      - i2b2-net
    depends_on:
      - i2b2-wildfly


  i2b2-wildfly:
    image: i2b2/i2b2-wildfly:${I2B2_WILDFLY_TAG}
    container_name: i2b2-wildfly
    environment:
      - DS_TYPE=${I2B2_DS_TYPE}
      - DS_IP=${I2B2_DS_IP}
      - DS_PORT=${I2B2_DS_PORT}
      - DS_PM_USER=${I2B2_DS_PM_USER}
      - DS_WD_USER=${I2B2_DS_WD_USER}
      - DS_HIVE_USER=${I2B2_DS_HIVE_USER}
      - DS_PM_PASS=${I2B2_DS_PM_PASS}
      - DS_WD_PASS=${I2B2_DS_WD_PASS}
      - DS_HIVE_PASS=${I2B2_DS_HIVE_PASS}

      - DS_CRC_IP=${I2B2_DS_CRC_IP}
      - DS_CRC_PORT=${I2B2_DS_CRC_PORT}
      - DS_CRC_USER=${I2B2_DS_CRC_USER}
      - DS_CRC_PASS=${I2B2_DS_CRC_PASS}
      - DS_CRC_DB=${I2B2_DS_CRC_DB}
      
      - DS_ONT_IP=${I2B2_DS_ONT_IP}
      - DS_ONT_PORT=${I2B2_DS_ONT_PORT}
      - DS_ONT_USER=${I2B2_DS_ONT_USER}
      - DS_ONT_PASS=${I2B2_DS_ONT_PASS}
      - DS_ONT_DB=${I2B2_DS_ONT_DB}
#    volumes:
#       - ./i2b2.war:/opt/jboss/wildfly/customization/i2b2.war
#      - ./postgresql-42.2.8.jar:/opt/jboss/wildfly/customization/postgresql-42.2.8.jar
#      - ./execute.sh:/opt/jboss/wildfly/customization/execute.sh
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - i2b2-net
    depends_on:
      - i2b2-pg


  i2b2-pg-vol-loader:
    image: i2b2/i2b2-pg-vol:${I2B2_PG_TAG}
    container_name: i2b2-pg-vol-loader
    volumes:
      - i2b2-pg-vol:/var/lib/postgresql/data
    entrypoint: /bin/sh
    networks:
      - i2b2-net

  i2b2-pg:
    image: postgres:12
    container_name: i2b2-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - i2b2-net
    volumes:
      - i2b2-pg-vol:/var/lib/postgresql/data
    depends_on:
      - i2b2-pg-vol-loader


networks:
  i2b2-net:
    name: i2b2-net
    driver: bridge

volumes:
  i2b2-mssql-vol:
    name: i2b2-mssql-vol
  i2b2-pg-vol:
    name: i2b2-pg-vol
